version: '3.3'
services:
  app:
    build:
      context: ./cryptoalarm-app/
      dockerfile: Dockerfile
    image: cryptoalarm-app
    container_name: cryptoalarm-app
    restart: always
#    command: python run.py --init
    depends_on:
      - "postgres"
      - "web"
    volumes:
      - ./cryptoalarm-app/python/config.json:/config.json
  web:
    build:
      context: ./cryptoalarm-web/
      dockerfile: Dockerfile
    image: cryptoalarm-web
    container_name: cryptoalarm-web
    restart: always
    working_dir: /var/www
    expose:
      - 9000
    depends_on:
      - "postgres"
    volumes:
      - web_data:/var/www
      - ./cryptoalarm-web/config/.env:/var/www/.env

  nginx:
    image: nginx:1.10
    working_dir: /var/www
    container_name: cryptoalarm-nginx
    restart: always
    depends_on:
      - "web"
    volumes:
      - web_data:/var/www
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HTTP_PORT}:80
#      - ${HTTPS_PORT}:443

  postgres:
    image: postgres:10
    container_name: cryptoalarm-postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: cryptoalarm-adminer
    restart: always
    depends_on:
      - "postgres"
    ports:
      - ${ADMINER_PORT}:8080


networks:
  default:
    external:
      name: ${NETWORK}

volumes:
  postgres_data:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/postgres"

  web_data:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/web"

#  storage_data:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/storage"

#  bootstrap_data:
#    driver: local-persist
#    driver_opts:
#      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/bootstrap"
